### ISSUE TITLE
Trouble with resolving HOST: filenames

### ISSUE THREAD

**Issue by iblowmymind** [JMlisp/og2vlm#1]
Hello,
While following the instructions (the FEP disk creation part, specifically) I've been hit with the following error message (I can't resolve any pathnames under HOST:/):
<img width="652" alt="Screenshot 2024-09-05 at 10 10 00 PM" src="https://github.com/user-attachments/assets/d9a54fad-a291-438b-aa56-af08bc4a1013">
Using DIS-EMB-HOST works alright but then I can't create a FEP disk image, because it specifically requires using host filesystem.
Is MAC-FS a custom package that was added to the vlod that's used for some of the Workgroup functionality (direct macOS filesystem access)? I am running on a Mac, but since I lack the Workgroup instructions I would not be able to set that up. Is there any way I can make it use regular host resolution instead?
<img width="608" alt="Screenshot 2024-09-05 at 10 17 48 PM" src="https://github.com/user-attachments/assets/1086a82f-a5b1-45fc-958c-c631c9a094ed">
Thanks!

(Also, just wanted to note: I am using an M1 Mac, and using UTM + Apple Virtualisation (needed for Rosetta 2 access on Linux for running x86_64 binaries on ARM Linux guests) running Debian 11 ARM and the instructions worked fine for me.)

PS: Oh, and I've also been getting a SEGV while trying to save the world:
```
genera: Unexpected SEGV at PC (nil) on VMA (nil)
backtrace returned 2 symbols
backtrace:
./genera(segv_handler+0x1f8)[0x55555558a808]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x13140)[0x7fffff7bd140]
```
Is this also related to HOST: not being accessible?
Update: Halting genera in general causes this, same addresses each time. I have to go and manually kill genera.

**Comment by JMlisp** [comment]
The problem you are facing is probably caused by one of the following: the type of Virtualisation (UTM Apple Virtualisation Linux), the Debian operating system (version 11 ARM) or the translation tool (Rosetta 2) for running binaries in Linux VMs on Apple Silicon. As explicitly mentioned in og2vlm-setup-v4.0, OG2VLM has been validated to run correctly on Intel Macs in Debian, only up to Version 9.4, both in VirtualBox up to V5.2.30 and on its own disk or partition. In particular, in order to access files of the host file system and create a FEP disk, the OG2 installation requires that the NFSv2 service is running. That is, it must not be disabled by any of the additional tools used, nor by Debian itself. As for MAC-FS, even if this package is part of the OG2 LMFS kit, it is only intended for Mac Ivory machines, not for Linux VLMs.

**Comment by iblowmymind** [comment]
The problem is, I can't run Debian 9 ARM builds because of an incompatibility of the kernel version and Apple's Virtualization framework. (It would just crash on startup) Debian 12, the latest version, outright removed NFSv2 from the kernel build arguments and used a version of nfs-utils after NFSv2 support was dropped, however simply sticking with Debian 11 solved both of those issues and I was able to set up NFSv2 shares.
And, after defining the site and the machines, I was able to use HOST:/ or J:/ to access the host filenames. This did mean that I had to skip using FEP, though. (I could've probably created an FEP disk after defining the site, but I haven't tried that and instead went with having my site on /var/lib/symbolics/rel-8-5/sys.sct (as a Unix filesystem directory) and it worked fine). I modified s.translations to point to that directory, even though I doubt it's necessary. (I think it's only used for the tape backup restoration step, and I skipped that since I already had a distribution) S: and SYS: resolves to my site properly.
I was also able to find out that my crashing issue is related to Xorg 6.9+ removing something used by VLM from xlib, and I was able to fix my crash by no-op'ing XLIB:CLOSE-DISPLAY, and while it is an ugly fix (prevents closing any displays) it kinda works? After the world is saved I have to manually kill the VLM by closing the cold boot stream after waiting a bit for safety, but it does actually get the world saved properly instead of it just crashing, and exiting Genera oddly works now since closing the display before prompting for the 3rd time in the cold boot stream doesn't matter as the VLM shutting down closes it anyway. Takes away the functionality of closing displays on demand though, but that would probably require modifying the VLM's source code to fix.
Besides all that, though, I now have a working VLM system with X forwarding! (I just run Debian headless and SSH forward VLM) Performance is, honestly, not noticeably different as Rosetta 2 is already very good at emulating x86_64. This provides a great way to run VLM on ARM Macs, and I would be glad to share my notes and the detailed steps I took if needed.
Thanks!

**Comment by JMlisp** [comment]
Great that you have managed to run OG2 on your M1 Mac. As mentioned already, NFSv2 is necessary for the OG2 installation, but once it is running with a Site already defined, access to files located on its Genera-host, i.e Jupiter, is done via NFSv3, which is part of the Genera-8-5e distribution. Open Peek, using Select P (F1 P on Mac), select the "File System" section, and for the "Host Jupiter", click on "Access path to J using NFS" and the "Describe" menu item. The instance variable values of #<NFS3::UNIX-NFS3-ACCESS-PATH J using NFS ....>, an object of flavor NFS3::UNIX-NFS3-ACCESS-PATH should be shown.

**Comment by iblowmymind** [comment]
Alright, I'll check for it when I can. Is there anything else I need to keep in mind while maintaining the system and using it? I don't have much experience with Genera, but I definitely am interested in it!

**Comment by JMlisp** [comment]
I assume you have the Initial OG2 world implemented for now. This enables you to proceed as described in og2vlm-setup-v4.0 and implement a Symbolics world that includes the most important OG2 systems. At this point you can then start using Genera and developing apps.  The "Select Help" command accelerator (F1 D on Mac) brings up the Document Examiner, which includes the complete Genera documentation set. "Select Help" (F1 F12 on Mac) provides the Select combinations for using other Genera activities. Enjoy OG2.

**Comment by iblowmymind** [comment]
Yep, loaded some systems and did a GC run. I have a Symbolics world set up now.
> The instance variable values of #<NFS3::UNIX-NFS3-ACCESS-PATH J using NFS ....>, an object of flavor NFS3::UNIX-NFS3-ACCESS-PATH should be shown.

I can see it is so, so I am using NFSv3! I'll keep NFSv2 on just in case.
I'll try out creating a Docker container for it now. Many thanks!

**Comment by iblowmymind** [comment]
Question, how do I remove a logical name translation I've defined? Seems like I shouldn't have kept the S: translation name in, and I've realised this after I installed all the systems and I was wondering if there was a way to do it without going back and resaving the world after redoing everything except defining the name. (The S: translation conflicts with the server's short name)

**Comment by JMlisp** [comment]
According to your comment provided 2 days ago s.translations was changed to point to the physical host "JUPITER:/var/lib/symbolics/rel-8-5/sys.sct" not taking into account that also other .translations exist not pointing to the physical host of your choice.

The s.translations file is used only while building the Symbolics.vlod. However OG2 after building the Symbolics world uses the sys.translations file, which must be reverted to its original state. You can change the content of .translations files in Zmacs but I doubt this will cure the issues you are facing.

Please note that in order to provide the appropriate support, OG2 installation onto your Mac Silicon should be made step by step, as described in the og2vlm-setup-v4.0 procedure.

That said, and since NFSv2 can be enabled, it might be worth to take into consideration to reinstall OG2 onto your Mac Silicon using a FEP and LMFS, as described in og2vlm-setup-v4.0, which in section "Prepare Debian and OG2 to host the LMFS system" also provides an alternative method to enable NFSv2 in Debian not requiring the installation of nfs-common.

**Comment by iblowmymind** [comment]
Traced back to the Symbolics.vlod creation step but omitted s.translations from ever being used this time by editing og2-translations.lisp (I don't use the FEP filesystem, so I don't need this to provide the sys translation for restoring to it) and I'm all good now. There was an error about C Documentation (it wanted 427, but I had 426) so I just manually loaded it afterwards and did a full GC again, and my system is working fine now.
Also created a user and did some user profile customizations.
![Screenshot 2024-09-08 at 8 51 24 PM](https://github.com/user-attachments/assets/df9cd976-06a6-4602-a148-a477889ead17)
Also tried loading Macsyma and NS. Found out the hard way you need a licensing password for them (which I don't own, sad).
But anyway, thanks for all your help and providing instructions for this distribution!

**Comment by JMlisp** [comment]
Glad to hear that OG2 on your M1 Silicon Mac works well, even if without LMFS. An Italian proverb says, who feels satisfied, enjoys. Please close this issue when possible. Thanks.

**Comment by iblowmymind** [comment]
Alright, mailed you.
